version: "3.1"
services:

  webserver:
    image: nginx:alpine
    container_name: m2-webserver
    working_dir: /application
    volumes:
      - magento-app:/application:delegated
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/m2.conf:/etc/nginx/m2.conf
    ports:
      - 80:80
      - 443:443
    networks:
      magento:

  php-fpm:
    build: php-fpm
    container_name: m2-php-fpm
    working_dir: /application
    volumes:
      - magento-app:/application:delegated
      - mercadopago-plugin:/application/app/code/MercadoPago
      - composer:/root/.config/composer/
      - ./php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
    networks:
      magento:

  db:
    image: mariadb:10.4
    container_name: m2-db
    environment:
      - MYSQL_ROOT_PASSWORD=1234qwer
      - MYSQL_DATABASE=magento2
      - MYSQL_USER=magento2
      - MYSQL_PASSWORD=magento2
    ports:
      - 3306:3306
    volumes:
      - magento-app:/app:delegated
      - magento-db:/var/lib/mysql
      - mariadb-cnf:/etc/mysql/conf.d
    healthcheck:
      test: mysqladmin ping -h localhost
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      magento:

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.2
    container_name: m2-elasticsearch
    environment:
      - node.name=es01
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      magento:
  
  mailhog:
    image: mailhog/mailhog
    container_name: m2-mailhog
    ports:
        - 1025:1025
        - 8025:8025
    networks:
        - magento

volumes:
  mariadb-cnf:
    driver_opts:
      type: none
      device: mysql/etc/mysql/conf.d
      o: bind
  magento-app:
    driver_opts:
      type: none
      device: app
      o: bind
  magento-db:
  composer:
  elasticsearch:
  mercadopago-plugin:
    driver_opts:
      type: none
      device: mercadopago/src/MercadoPago
      o: bind

networks:
  magento:
    driver: bridge
